全てのワーカーが成功したらJobSetを成功とする例

diff --git a/jobset/jobset.yaml b/jobset/jobset.yaml
--- a/jobset/jobset.yaml
+++ b/jobset/jobset.yaml
@@ -19,13 +19,28 @@ spec:
       replicas: 2
       template:
         spec:
+          backoffLimit: 0
           template:
             spec:
               containers:
               - name: worker
                 image: busybox
                 command: ["/bin/sh"]
-                args: ["-c", "echo 'start'; sleep 10; echo 'end'"]
+                args:
+                  - "-c"
+                  - |
+                    echo 'start'
+                    sleep 10
+                    if [ $((RANDOM % 2)) -eq 0 ]; then
+                      echo 'failed'
+                      exit 1
+                    else
+                      echo 'success'
+                    fi
       dependsOn:
       - name: leaders
-        status: Complete
+        status: Ready
+  successPolicy:
+    operator: All
+    targetReplicatedJobs:
+      - workers
